x-net: &net
  cap_add:
    - NET_ADMIN

services:
  node1:
    <<: *net
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: dht-cluster
    hostname: node1
    tty: true
    ports:
      - "20000:20000"
      - "21001:21001"
    command: ["-addr", "node1", "-port", "20000", "-cmd-port", "21001"]

  node2:
    <<: *net
    image: dht-cluster
    hostname: node2
    tty: true
    ports:
      - "20001:20000"
      - "21002:21001"
    command: ["-addr", "node2", "-port", "20000", "-join", "node1:20000", "-cmd-port", "21001"]

  node3:
    <<: *net
    image: dht-cluster
    hostname: node3
    tty: true
    ports:
      - "20002:20000"
      - "21003:21001"
    command: ["-addr", "node3", "-port", "20000", "-join", "node1:20000", "-cmd-port", "21001"]